spring.application.name=FitnessMonolith

spring.datasource.url=jdbc:mysql://localhost:3306/fitness_db
spring.datasource.username=vaibhaovk
spring.datasource.password=vaibhao
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true